import ZoomableImage from "../components/ZoomableImage";
import Connector from "../components/Connector";
import Page from "../components/Page";
import { Banner, Section, Paragraph } from "../components/Projects";
import { getProject } from "../data/projects";

const project = getProject("caseai");

const CaseAI = () => {
  return (
    <Page>
      <Banner project={project} />

      <div className="project-body">
        <Connector />
        <Section title="CaseAI">
          <Paragraph>
            A procedural investigation game powered by AI. Players take on the role of a detective
            exploring a mysterious murder case generated by an LLM agent. The system determines the
            murder weapon, motive, timeline, and witnesses, and invents additional lore.
          </Paragraph>
        </Section>

        <Connector />
        <Section title="Gameplay">
          <Paragraph>
            Players can navigate a top-down map of a smithy interior, interact with characters, and
            ask questions in natural language. Each character is an LLM agent with a memory that
            tracks interactions for the session, providing clues, alibis, or distractions. Clues
            are automatically gathered on a clue board.
          </Paragraph>

          <ZoomableImage src="/projects/caseAI/investigate.png" />

          <Paragraph>
            <strong>Watson</strong> is a Prolog-based symbolic AI that tries to solve the murder
            using the same clues. The goal is to identify the murderer before Watson does.
          </Paragraph>

          <ZoomableImage src="/projects/caseAI/scenescreen.png" />
          <ZoomableImage src="/projects/caseAI/clues.png" />
          <ZoomableImage src="/projects/caseAI/endscreen.png" />
        </Section>

        <Connector />
        <Section title="Technology">
          <Paragraph>
            CaseAI is a static web application hosted on{" "}
            <a href="https://hpn4.github.io/CaseAI" target="_blank" rel="noopener noreferrer">
              GitHub Pages
            </a>
            . The frontend is built with <strong>HTML, CSS, and JavaScript</strong>. LLM
            interactions are performed via the OpenAI API (you need to provide an API key to play
            the game), and Watson runs with <strong>tau-prolog</strong> in the browser.
          </Paragraph>

          <ZoomableImage src="/projects/caseAI/homescreen.png" />
        </Section>
      </div>
    </Page>
  );
};

export default CaseAI;
