import React from "react";

import ZoomableImage from "../components/ZoomableImage"
import BackCircle from "../components/BackCircle"
import { Banner, Section, Paragraph } from "../components/Projects"

const CaseAI = () => {
  return (
    <>
      <BackCircle lastCircle={false} to={"/projects"}/>
      <Banner
        banner="/projects/caseAI/scenescreen.png"
        title="CaseAI"
        subtitle="An AI-generated murder game."
        techs={[
          "javascript", "html5", "css3", "prolog", "json",           // languages
          "github" // DevOps
        ]}
        duration="1 month"
        groupSize="2 with Pierre B. and myself."
        role="Backend development (agent system & Watson) and asset sourcing."
        link="https://github.com/Hpn4/CaseAI/"
      />

      <div className="project-body">
        <Section title="CaseAI">
          <Paragraph>
            A procedural investigation game powered by AI. Players take on the role of a detective exploring a mysterious murder case generated by a LLM agent. The system determines the murder weapon, motive, timeline, witnesses, and invents additional lore.
          </Paragraph>

        </Section>

        <Section title="Gameplay">
          <Paragraph>
            Players can navigate a top-down map of a smithy interior, interact with characters, and ask questions in natural language. Each character is an LLM agent with a memory that tracks interactions for the session, providing clues, alibis, or distractions. Clues are automatically gathered on a clue board.
          </Paragraph>

          <ZoomableImage src="/projects/caseAI/investigate.png" />

          <Paragraph>
            <strong>Watson</strong> is a Prolog-based symbolic AI that tries to solve the murder using the same clues. The goal is to identify the murderer before Watson does.
          </Paragraph>

          <ZoomableImage src="/projects/caseAI/scenescreen.png" />
          <ZoomableImage src="/projects/caseAI/clues.png" />
          <ZoomableImage src="/projects/caseAI/endscreen.png" />
        </Section>

        <Section title="Technology">
          <Paragraph>
            CaseAI is a static web application hosted on <a href="https://hpn4.github.io/CaseAI" target="_blank" rel="noopener noreferrer">GitHub Pages</a>. The frontend is built with <strong>HTML, CSS, and JavaScript</strong>. LLM interactions are performed via OpenAI API (you need to provide an API key in order to play the game), and Watson runs with <strong>tau-prolog</strong> in the browser.
          </Paragraph>

          <ZoomableImage src="/projects/caseAI/homescreen.png"/>
        </Section>
      </div>

    </>
  );
};

export default CaseAI;
