import Connector from "../components/Connector";
import Page from "../components/Page";
import ZoomableImage from "../components/ZoomableImage";
import { Banner, Section, Paragraph } from "../components/Projects";
import { getProject } from "../data/projects";

const project = getProject("minecraft-texture-gen");

const MinecraftTextureGen = () => {
  return (
    <Page>
      <Banner project={project} />

      <div className="project-body">
        <Connector />
        <Section title="Overview">
          <Paragraph>
            Deep generative models trained to produce 16x16 Minecraft style block and item
            textures, built as a group project of three at EPITA. Two architectures are
            implemented and compared: a diffusion U-Net and a VQ-VAE with a PixelCNN prior. My part
            was the data pipeline: scraping, cleaning, filtering and grouping the texture dataset
            the models are trained on.
          </Paragraph>
        </Section>

        <Connector />
        <Section title="Data pipeline">
          <Paragraph>
            <ul>
              <li>A scraper pulls resource packs from CurseForge and unpacks their item and block textures.</li>
              <li>A cleaning pass filters the raw dump: wrong size, wrong extension, broken images, animated textures, near duplicates (perceptual hashing), and categories with too few examples, each sorted into its own folder rather than just discarded.</li>
              <li>Each remaining texture is auto-captioned with CLIP zero-shot classification against a fixed vocabulary of shapes and colors, producing the conditioning used to train and label the dataset.</li>
            </ul>
          </Paragraph>
        </Section>

        <Connector />
        <Section title="Models">
          <Paragraph>
            A DDPM U-Net (500 timesteps, DDIM sampling for fast inference) and a VQ-VAE with a
            gated masked PixelCNN trained as an autoregressive prior over its discrete latent
            codes. A resource pack exporter then walks a vanilla Minecraft resource pack and
            replaces every item texture with a freshly generated one.
          </Paragraph>
        </Section>

        <Connector />
        <Section title="Results">
          <Paragraph>U-Net diffusion sampling, from noise to a finished item texture:</Paragraph>
          <div className="project-image-row">
            <ZoomableImage src="/projects/minecraft-texture-gen/boat.gif" alt="Diffusion sampling of a boat texture, from noise to finished result" />
            <ZoomableImage src="/projects/minecraft-texture-gen/sword.gif" alt="Diffusion sampling of a sword texture, from noise to finished result" />
            <ZoomableImage src="/projects/minecraft-texture-gen/pickaxe.gif" alt="Diffusion sampling of a pickaxe texture, from noise to finished result" />
          </div>
          <Paragraph>A batch of axe textures generated by the same model:</Paragraph>
          <ZoomableImage src="/projects/minecraft-texture-gen/conditionned.png" alt="Grid of generated axe textures" />
        </Section>
      </div>
    </Page>
  );
};

export default MinecraftTextureGen;
